### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by danil31219as** [DAMO-NLP-SG/VideoLLaMA2#1]
When will the weights be available?

**Comment by lixin4ever** [comment]
Thank you for your attention.

We are finalizing the draft of the technical report and the model weights will be online together with the technical report, hopefully by the end of Friday.

**Comment by lixin4ever** [comment]
@danil31219as The weights are now available at: https://huggingface.co/DAMO-NLP-SG/VideoLLaMA2-7B .

**Comment by SeanChenxy** [comment]
Hi, what is the difference between Base and Chat weights?

**Comment by lixin4ever** [comment]
Base refers to the model pre-trained with large-scale caption-only data (i.e., the first-stage model) while Chat model is further fine-tuned from Base model (i.e., the second-stage model).
