### ISSUE TITLE
Audio processing

### ISSUE THREAD

**Issue by danil31219as** [DAMO-NLP-SG/VideoLLaMA2#10]
process_video function does not contain audio processing (following the example from readme)

**Comment by lixin4ever** [comment]
Thanks for your attention, we are still cleaning the code related to the audio-language branch and it will be available soon.

**Comment by Shubh8434** [comment]
is it available i have to do multimodal inference of audio and video

**Comment by Cece1031** [comment]
I need audio too, when can it be released?

**Comment by xinyifei99** [comment]
Thanks for your attention! You can switch to the audio_visual branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) and clone the repository to train and inference the audio_visual branch.
