### ISSUE TITLE
audio information

### ISSUE THREAD

**Issue by sjghh** [DAMO-NLP-SG/VideoLLaMA2#102]
Thank you for your excellent work. I would like to ask, if I use my own dataset for fine-tuning, can the model learn the information from the audio? I appreciate your response.

**Comment by xinyifei99** [comment]
Thanks for your attention! You can switch to the audio_visual branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) and clone the repository to train and inference the audio_visual branch.
