### ISSUE TITLE
Demo Question

### ISSUE THREAD

**Issue by sjghh** [DAMO-NLP-SG/VideoLLaMA2#103]
![image](https://github.com/user-attachments/assets/82ccb581-3618-4510-8c0c-0965bca6997e)
When I ran the demo locally, I encountered this issue. Is it a problem with my deployment, or could it be an error with the weights?

**Comment by sjghh** [comment]
model_path = '/data/video-llama2/VideoLLaMA2-main/VideoLLaMA2-7B-16F'

**Comment by clownrat6** [comment]
/data seems to be a absolute path. Is it right? Please check if the model is succesfully loaded again. 🙏

**Comment by sjghh** [comment]
> 🙏

Thank you for your response. I found that there was an issue with the weights I downloaded, but I have now resolved it. 

Additionally, I’d like to ask, when will the audio branch be available?🙏

**Comment by lixin4ever** [comment]
@sjghh Hi, the checkpoints and the inference code for VideoLLaMA2-AV are already publicly available, please re-clone the repo and switch to the audio-visual branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) for more details.
