### ISSUE TITLE
You are using a model of type mistral to instantiate a model of type videollama2_mistral. This is not supported for all configurations of models and can yield errors.

### ISSUE THREAD

**Issue by hufflepuff0596** [DAMO-NLP-SG/VideoLLaMA2#107]
I encountered this alert while fine-tuning with LoRA. Is this normal?

**Comment by clownrat6** [comment]
This warning is normal. Because we define a `videollama2_mistral` type config/model, this warning will happen when we use mistral weights to initialize it.
