### ISSUE TITLE
AV ckpt inference error

### ISSUE THREAD

**Issue by kk94wang** [DAMO-NLP-SG/VideoLLaMA2#109]
Hi there,

Thanks for releasing the new av ckpt, but it seems your codebase hasn't been updated yet. So when running inference with the sample code, it gets error of 
`TypeError: process_video() got an unexpected keyword argument 'va'`
Do you have any timeline of av version updates? 

Bests,

**Comment by xinyifei99** [comment]
Thanks for your attention! You can switch to the audio_visual branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) and clone the repository to run inference for audio_visual related tasks.

**Comment by LiangMeng89** [comment]
> Hi there,
> 
> Thanks for releasing the new av ckpt, but it seems your codebase hasn't been updated yet. So when running inference with the sample code, it gets error of `TypeError: process_video() got an unexpected keyword argument 'va'` Do you have any timeline of av version updates?
> 
> Bests,

Hello,I'm a phD student from ZJU, I also use videollama2 to do my own research,we create a WeChat group to discuss some issues of videollama2 and help each other,could you join us? Please contact me: WeChat number == LiangMeng19357260600, phone number == +86 19357260600,e-mail == liangmeng89@zju.edu.cn.
