### ISSUE TITLE
The base model used from hugging face for Audio Visual question answering is not at all working

### ISSUE THREAD

**Issue by asmit203** [DAMO-NLP-SG/VideoLLaMA2#119]
I used the following script
```python
import sys
sys.path.append('./')
from videollama2 import model_init, mm_infer
from videollama2.utils import disable_torch_init
import argparse

def inference(args):

    model_path = args.model_path
    model, processor, tokenizer = model_init(model_path)

    if args.modal_type == "a":
        model.model.vision_tower = None
    elif args.modal_type == "v":
        model.model.audio_tower = None
    elif args.modal_type == "av":
        pass
    else:
        raise NotImplementedError
    
    # Audio-visual Inference
    audio_video_path = "assets/00003491.mp4"
    preprocess = processor['audio' if args.modal_type == "a" else "video"]
    audio_video_tensor = preprocess(audio_video_path, va=True if args.modal_type == "av" else False)
    question = f"Please describe the video with audio information."

    output = mm_infer(
        audio_video_tensor,
        question,
        model=model,
        tokenizer=tokenizer,
        modal='audio' if args.modal_type == "a" else "video",
        do_sample=False,
    )

    print(output)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('--model-path', help='', required=False, default='DAMO-NLP-SG/VideoLLaMA2.1-7B-AV')
    parser.add_argument('--modal-type', choices=["a", "v", "av"], help='', required=True)
    args = parser.parse_args()

    inference(args)
```

and the cli command used `python inf.py --modal-type av`

The problem I faced
<img width="1724" alt="image" src="https://github.com/user-attachments/assets/0ee0578b-cb59-4126-9c24-74b9aa331b43">
<img width="1714" alt="image" src="https://github.com/user-attachments/assets/5a7a1f31-2e41-4bf6-ba91-7c6fcb16333a">
can anyone please tell me why is it behaving such a way?

**Comment by asmit203** [comment]
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/4099b33e-249f-49d3-b421-bdbe238c680b">
The problem is still there even after I removed the cached model and again restarted the local demo

**Comment by xinyifei99** [comment]
Hi, there! Which branch do you use? You should use this branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) for inference.

**Comment by asmit203** [comment]
> Hi, there! Which branch do you use? You should use this branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) for inference.

Yes I have used the audio_visual branch.

**Comment by Haoyu-ha** [comment]
I have the same problem.

**Comment by Haoyu-ha** [comment]
> I have the same problem.

I found this to be the case whenever there is an audio modality in the input.

**Comment by LiangMeng89** [comment]
> > I have the same problem.
> 
> I found this to be the case whenever there is an audio modality in the input.

Hello,I'm a phD student from ZJU, I also use videollama2 to do my own research,we create a WeChat group to discuss some issues of videollama2,could you join us? Please contact me: WeChat number == LiangMeng19357260600, phone number == +86 19357260600,e-mail == liangmeng89@zju.edu.cn.

**Comment by xinyifei99** [comment]
Hi, we have re-tested locally and asked colleagues who had no experience with the videollama2 project to build a videollama2 environment from scratch to run the inference demo, but the results are all fine. So we are currently unable to locate the problem. Perhaps you can disclose more details to help us locate the problem.

**Comment by asmit203** [comment]
@xinyifei99 thanks
Yeah issue is resolved for now. I rebuilt the whole environment and it worked.
though a small help is required can you please lemme know why the following error is still there
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/89846c95-f2b7-4aa3-b9cd-80d18314e885">

**Comment by asmit203** [comment]
Thank you I think all the problem is sorted hence closing the issue.
