### ISSUE TITLE
About dataset and audio part

### ISSUE THREAD

**Issue by jmliu206** [DAMO-NLP-SG/VideoLLaMA2#12]
Thank you for your great work. I have the following questions:

1. Will you release the dataset mentioned in the paper? Currently, the GitHub repository only seems to have the code for training with the video-llava dataset. How much improvement does your dataset have compared to video-llava?

2. It seems that the current code does not include the audio part. Will this be provided later? If we do not perform Audio-Language Training and Audio-Video Joint Training, will it affect the performance on Video QA benchmarks?

Looking forward to your reply. Thanks!

**Comment by lixin4ever** [comment]
1.1: Currently we have no plan to release the dataset we use to train VideoLLaMA 2, however, almost all of the data we use are from the open-source community (see Table 2-4) and it is not difficult to create a comparable or even better data mixture based on what we have mentioned.
1.2: The numbers in Table 1 and Table 5 should tell the difference 
2.1: Yes, you are right. We are still cleaning the code of the audio-language branch, it will be available soon.
2.2: It doesn't matter. The results of the Video QA benchmarks are from the vision-only VideoLLaMA 2.

Thanks for your interest.

**Comment by jmliu206** [comment]
Thank you for your quick response!
