### ISSUE TITLE
Continue training with audio_visual branch

### ISSUE THREAD

**Issue by Danielement321** [DAMO-NLP-SG/VideoLLaMA2#128]
Thanks for your awesome work!

I've met some problems when va_joint training with my custom data. I want to finetune VideoLlama2 with custom data for downstream work. My data is not very much so I want to start with the final released model `VideoLLaMA2.1-7B-AV` and finetune it with videos. Can you provide a script for continuous training with  `VideoLLaMA2.1-7B-AV` 

Thanks again for your work!

**Comment by ffcarina** [comment]
I also encountered issues while attempting fine-tuning. We hope the authors can provide an official script for further fine-tuning (LoRA) the `VideoLLaMA2.1-7B-AV` model. 
Thanks for your great work!

**Comment by xinyifei99** [comment]
Sorry, we currently do not have support for using lora for audio-visual training.

**Comment by Danielement321** [comment]
Thanks for your reply!
Could you please provide a script for continuous training with released `VideoLLaMA2.1-7B-AV` model? Thanks a lot!

**Comment by ffcarina** [comment]
> Sorry, we currently do not have support for using lora for audio-visual training.

@xinyifei99 Thank you for your prompt response! 
Could you provide a script for further fine-tuning? Would it suffice to simply change the `model_path` in [va_joint.sh](https://github.com/DAMO-NLP-SG/VideoLLaMA2/blob/audio_visual/scripts/custom/va_joint.sh) to `VideoLLaMA2.1-7B-AV` and set `audio_tower` to `VideoLLaMA2.1-7B-AV/audio_tower.bin`? Additionally, how much GPU memory would be required to support such full fine-tuning?
