### ISSUE TITLE
Why the model VideoLLaMA2.1-7B-AV which text decoder is based on Qwen2-7B-Instruct can not output Chinese?

### ISSUE THREAD

**Issue by lilac08** [DAMO-NLP-SG/VideoLLaMA2#134]
Hi, I'm trying to let this model output Chinese answer, but it only output English even I ask it to answer in Chinese.  Is there any way that I can try Chinese output?

**Comment by xinyifei99** [comment]
Hello, our AV model is currently only trained with English datasets, so it may lead to poor inference performance in Chinese.
