### ISSUE TITLE
Low performance while reproducing ClothoAQA

### ISSUE THREAD

**Issue by G-JWLee** [DAMO-NLP-SG/VideoLLaMA2#139]
Hi, thank you for your great work.

I ran VideoLLaMA2.1-7B-AV with the ClothoAQA evaluation benchmark, but received the scores below:

Overall Accuracy: 59.02% Total Responses: 14706
Binary Accuracy: 75.29% Total Binary Responses: 9804

I believe the reported performance is 71.02% in 'Overall Accuracy'.

We download the data and jsonl files from https://github.com/QwenLM/Qwen-Audio/blob/main/eval_audio/EVALUATION.md and process clothoqaq_eval.jsonl to fit into the ClothoAQADataset class in inference_audio.py.

Also, I found that in clothoqaq_eval.jsonl, there are multiple possible answers. 
{"audio": "clothoqa/audio_files/helicopter.wav", "gt": "road", "source": "clothoaqa_val", "question": "Where is this sound taking place?"}
{"audio": "clothoqa/audio_files/helicopter.wav", "gt": "train", "source": "clothoaqa_val", "question": "Where is this sound taking place?"}
{"audio": "clothoqa/audio_files/helicopter.wav", "gt": "airport", "source": "clothoaqa_val", "question": "Where is this sound taking place?"}

which makes the answers in merge.json fail to predict.
{"id": 12111, "question": "Question: Where is this sound taking place?\nAnswer the question using a single word.", "answer": "road", "pred": "AIRPORT"}
{"id": 12112, "question": "Question: Where is this sound taking place?\nAnswer the question using a single word.", "answer": "train", "pred": "AIRPORT"}
{"id": 12113, "question": "Question: Where is this sound taking place?\nAnswer the question using a single word.", "answer": "airport", "pred": "AIRPORT"}

Then, even though the VideoLLaMA2.1-7B-AV model got the correct answer ('AIRPORT'), the benchmark makes the two other questions wrong.

**Comment by xinyifei99** [comment]
For the ClothoAQA dataset, we did not follow Qwen-audio, but the *_clean.csv file in the repository https://github.com/GeWu-Lab/MWAFM

**Comment by G-JWLee** [comment]
Thank you for the clarification! 
How about TUT2017, VocalSound, and MUSIC-QA (Audio-Visual QA)? Can you clarify where the evaluation json source files are from?

**Comment by Bashima** [comment]
@xinyifei99 Can you please share the evaluation json files for MUSIC-QA?

@G-JWLee did you figure it out?
