### ISSUE TITLE
Video LLaVA dataset issue

### ISSUE THREAD

**Issue by ayaan-together** [DAMO-NLP-SG/VideoLLaMA2#20]
In the finetuning phase, I get [h264 @ 0x1f0acd40] mmco: unref short failure and [mov,mp4,m4a,3gp,3g2,mj2 @ 0x19a50700] moov atom not found. It does not stop training though.

Also, could you tell me how many videos there are in valley and videochatgpt datasets. The download I have has many missing files.

**Comment by lixin4ever** [comment]
Hi Ayaan, good to receive your feedback.

The warning does not indicate the FileNotFound error but some internal issues of the input video, which does not affect the calculation of visual features according to this [thread](https://github.com/dmlc/decord/issues/177).

So, the training should be fine and you can just ignore the warning.

**Comment by ayaan-together** [comment]
Perfect!

**Comment by sjghh** [comment]
I encountered the following issue during the fine-tuning process. After checking the original video file, I found that it couldn't be opened. Could it be that the original file is corrupted, or did something go wrong during transmission? I appreciate your response. 
[10:21:05] /github/workspace/src/video/video_reader.cc:83: ERROR opening: /data/video-llama2/VideoLLaMA2-main/datasets/videollava_sft/videochatgpt_tune/v_B7Ddfw2PXOI.mp4, Invalid data found when processing input
Traceback (most recent call last):
  File "/data/video-llama2/VideoLLaMA2-main/videollama2/train.py", line 315, in __getitem__
    video = process_video(video_file, video_processor, aspect_ratio=self.data_args.image_aspect_ratio, num_frames=num_frames)
  File "/data/video-llama2/VideoLLaMA2-main/videollama2/mm_utils.py", line 155, in process_video
    vreader = VideoReader(video_path, ctx=cpu(0), num_threads=1)
  File "/opt/conda/envs/Videollama2/lib/python3.9/site-packages/decord/video_reader.py", line 57, in __init__
    raise RuntimeError("Error reading " + uri + "...")
RuntimeError: Error reading /data/video-llama2/VideoLLaMA2-main/datasets/videollava_sft/videochatgpt_tune/v_B7Ddfw2PXOI.mp4...
Encounted error when reading video /data/video-llama2/VideoLLaMA2-main/datasets/videollava_sft/videochatgpt_tune/v_B7Ddfw2PXOI.mp4, use 147764-th example instead!!!
