### ISSUE TITLE
Why the sceneDetect code didn't use at all

### ISSUE THREAD

**Issue by lucasjinreal** [DAMO-NLP-SG/VideoLLaMA2#23]
Sampling training data with SceneDetect will cost too much time?

**Comment by lixin4ever** [comment]
Thanks for your interest.

You are correct, scene detection is already very slow and encoding multiple segmented scenes (instead of one single video) will make the whole process much more time-consuming. 

Note that this is just an experimental feature and **NOT** used in the current release.
