### ISSUE TITLE
Question on compute

### ISSUE THREAD

**Issue by Utkarsh4430** [DAMO-NLP-SG/VideoLLaMA2#3]
Hey! Great work, guys! I just wanted to know how much compute did it take to pretrain the model. The number and size of GPUs and the number of hours the model was trained.
Thanks!

**Comment by sennnnn** [comment]
Based on our experiment settings, pretraing stage and finetuning stage take around 5~6 hours and 16~17 hours on 32 A100, respectively.

**Comment by pritamqu** [comment]
did you use 40GB or 80GB A100?

**Comment by lixin4ever** [comment]
> did you use 40GB or 80GB A100?

We use 80GB A100/A800s.
