### ISSUE TITLE
Evaluation after fine-tuning

### ISSUE THREAD

**Issue by Hyu-Zhang** [DAMO-NLP-SG/VideoLLaMA2#32]
Thanks for releasing the code for the great work. 
I fine-tuned on my own data and saved the adapter file as shown in Figure 1. 
![image](https://github.com/DAMO-NLP-SG/VideoLLaMA2/assets/103087694/cb6c8569-4307-4275-b536-21aa253d9eee)
Then I want to evaluate the fine tuning results so execute the command "python3 videollama2/eval/inference_video_oqa_vcgpt.py --model-path /VideoLLaMA2/work_dirs/videollama2_vllava/finetune_videollama2_vllava_lora ..." but I encountered an error.
`OSError: Can't load tokenizer for '/VideoLLaMA2/work_dirs/videollama2_vllava/finetune_videollama2_vllava_lora'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/VideoLLaMA2/work_dirs/videollama2_vllava/finetune_videollama2_vllava_lora' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.`
I considered that the base model might not be loaded, so I modified /VideoLLaMA2/videollama2/__init__.py
```
tokenizer, model, processor, context_len = load_pretrained_model(model_path, None, model_name)
->tokenizer, model, processor, context_len = load_pretrained_model(model_path, "/Mistral-7B-Instruct-v0.2", model_name)
```
Unfortunately, another error occurred "AttributeError: 'MistralConfig' object has no attribute 'attention_bias'".

Can you tell me how to properly implement the evaluation after fine-tuning?

**Comment by sennnnn** [comment]
Hi, is it still facing some bugs? We try to resolve some lora bugs via this pr #36

**Comment by LiangMeng89** [comment]
> Thanks for releasing the code for the great work. I fine-tuned on my own data and saved the adapter file as shown in Figure 1. ![image](https://private-user-images.githubusercontent.com/103087694/345262460-cb6c8569-4307-4275-b536-21aa253d9eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MjM0NzcsIm5iZiI6MTczMTUyMzE3NywicGF0aCI6Ii8xMDMwODc2OTQvMzQ1MjYyNDYwLWNiNmM4NTY5LTQzMDctNDI3NS1iNTM2LTIxYWEyNTNkOWVlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxODM5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjA3NGU1MzNiMDQ0NTk3YTA5NDYxMzgwZjc0NTQ5ZDc3YjA4NDQwNWQ5NDVhZjYzNWIxMTQzMTExNjk1ODRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1o2vaLNaoPQHvtP4sWHk3DnUwlcizLFpl3LgHXTavjE) Then I want to evaluate the fine tuning results so execute the command "python3 videollama2/eval/inference_video_oqa_vcgpt.py --model-path /VideoLLaMA2/work_dirs/videollama2_vllava/finetune_videollama2_vllava_lora ..." but I encountered an error. `OSError: Can't load tokenizer for '/VideoLLaMA2/work_dirs/videollama2_vllava/finetune_videollama2_vllava_lora'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/VideoLLaMA2/work_dirs/videollama2_vllava/finetune_videollama2_vllava_lora' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.` I considered that the base model might not be loaded, so I modified /VideoLLaMA2/videollama2/**init**.py
> 
> ```
> tokenizer, model, processor, context_len = load_pretrained_model(model_path, None, model_name)
> ->tokenizer, model, processor, context_len = load_pretrained_model(model_path, "/Mistral-7B-Instruct-v0.2", model_name)
> ```
> 
> Unfortunately, another error occurred "AttributeError: 'MistralConfig' object has no attribute 'attention_bias'".
> 
> Can you tell me how to properly implement the evaluation after fine-tuning?

Hello,I'm a phD student from ZJU, I also use videollama2 to do my own research,we create a WeChat group to discuss some issues of videollama2 and help each other,could you join us? Please contact me: WeChat number == LiangMeng19357260600, phone number == +86 19357260600,e-mail == liangmeng89@zju.edu.cn.
