### ISSUE TITLE
到底用什么依赖包？？？自相矛盾

### ISSUE THREAD

**Issue by tsiens** [DAMO-NLP-SG/VideoLLaMA2#33]
videollama2 1.0 depends on tokenizers==0.15.1
 transformers 4.41.2 depends on tokenizers<0.20 and >=0.19

**Comment by tsiens** [comment]
![image](https://github.com/DAMO-NLP-SG/VideoLLaMA2/assets/24999801/7936b0c5-c5af-4e5b-a698-4cb5d5291c5b)
？？？pydantic？？？

**Comment by tsiens** [comment]
经过验证，yaproject.toml pydantic应该是大于2，否则运行报错transformers改成4.37.2

**Comment by sennnnn** [comment]
> ![image](https://private-user-images.githubusercontent.com/24999801/345297256-7936b0c5-c5af-4e5b-a698-4cb5d5291c5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDE2MjcsIm5iZiI6MTcyMDAwMTMyNywicGF0aCI6Ii8yNDk5OTgwMS8zNDUyOTcyNTYtNzkzNmIwYzUtYzVhZi00ZTViLWE2OTgtNGNiNWQ1MjkxYzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEwMDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlODIyMDlmNzkxMGI0MTJjOWY3NmU0ZTAwMjk5N2JjOTljZTExNzk2YmMwYTU2MjE4ZDcxZjgzOGNkMGRlMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vjjPJTGczX34MokeMewUTrfDLaz7bCZUfCZFIInS-Ro) ？？？pydantic？？？

我们已经修复了 requirements.txt 和 pyproject.toml 的版本不一致。实际上，requirements.txt 和 pyproject.toml 是相互独立的，分别对应两种安装方式，可以任选一种方式进行安装。

**Comment by sennnnn** [comment]
> videollama2 1.0 depends on tokenizers==0.15.1 transformers 4.41.2 depends on tokenizers<0.20 and >=0.19

当前的 requirements.txt 和 pyproject.toml 应该是设置了 transformers==4.37.2，暂时还不支持 transformers 4.41.2。
