### ISSUE TITLE
The setting of subtitles

### ISSUE THREAD

**Issue by caichaoxiang** [DAMO-NLP-SG/VideoLLaMA2#35]
Hi,

I saw a problem with the subtitles setting in the videollama2 paper, but recently I saw that the w subtitles indicator has been added on the videomme Leaderboard (https://video-mme.github.io/home_page.html#leaderboard). Has this issue been fixed?
![1](https://github.com/DAMO-NLP-SG/VideoLLaMA2/assets/113684730/ad6c6d6e-eb79-4d96-99f4-47ee2e3fc3f9)
![2](https://github.com/DAMO-NLP-SG/VideoLLaMA2/assets/113684730/68e3b262-679d-4673-b630-926dbeb45e4b)

**Comment by lixin4ever** [comment]
Yes, we contacted the VideoMME team and eventually resolved this issue. BTW, we haven't updated the arxiv paper with the new results (but will do it soon), please refer to the official leaderboard for the potential comparative study.
