### ISSUE TITLE
Finetune with LoRA and QLoRA

### ISSUE THREAD

**Issue by thisurawz1** [DAMO-NLP-SG/VideoLLaMA2#5]
Can you provide a detailed guide on how to use LoRA or QLoRA finetuning of VideoLLaMA2 and also for inference.  Moreoever, can you provide the guide on how to make the finetuning dataset for images , videos and both.

**Comment by sennnnn** [comment]
Parameter-efficient finetuning~(e.g., Lora/Qlora) is under developing. Please wait a moment, this part is coming up soon.

**Comment by thisurawz1** [comment]
If you don't mind, can you tell us when? Also, is it possible to make a WeChat group and share the QR here. so we can post our problems related to Videollama2 there.

**Comment by lixin4ever** [comment]
Sorry, due to the lack of manpower, we only respond to the Github issues, and no plan to maintain a WeChat group regarding VideoLLaMA2.

**Comment by thisurawz1** [comment]
thank you so much. can you please provide a detailed guide on finetuning using QLoRA? because when with the .sh file it's so confusing how to do it.

**Comment by thisurawz1** [comment]
how much minimum ram do we need for LoRA fine-tuning?

**Comment by sennnnn** [comment]
Suppose adopting `8 frame & 4 batch_size` settings, the memory cost on a single A100 is shown as below:
|  Model  | Finetuning | Memory |
|  ----       | ----           | ---            |
| VideoLLaMA2-7B   | full-finetuning | OOM |
| VideoLLaMA2-7B   | lora-finetuning | ≈44GB |
| VideoLLaMA2-7B   | qlora-finetuning | ≈36GB |

If your device can't cover such a memory cost, you can modify `LOCAL_BATCH_SIZE` to reduce the cost.
