### ISSUE TITLE
How to eval egoschema and perception_test？

### ISSUE THREAD

**Issue by caichaoxiang** [DAMO-NLP-SG/VideoLLaMA2#50]
Hi,

After inference, I have obtained the output files of egochema and perception_test. However, these two datasets do not directly get the evaluation results like videomme. How can I evaluate the results later?

**Comment by lixin4ever** [comment]
To obtain the numbers on EgoSchema and Perception Test MCQA, you need to submit the model outputs to the official evaluation server. Here are the links of the evaluation servers:
- Egoschema: https://www.kaggle.com/competitions/egoschema-public/submissions
- Perception Test MCQA: https://eval.ai/web/challenges/challenge-page/2091/submission

**Comment by LiangMeng89** [comment]
> Hi,
> 
> After inference, I have obtained the output files of egochema and perception_test. However, these two datasets do not directly get the evaluation results like videomme. How can I evaluate the results later?

Hello,I'm a phD student from ZJU, I also use videollama2 to do my own research,we create a WeChat group to discuss some issues of videollama2 and help each other,could you join us? Please contact me: WeChat number == LiangMeng19357260600, phone number == +86 19357260600,e-mail == liangmeng89@zju.edu.cn.
