### ISSUE TITLE
Datasets download for MSVC

### ISSUE THREAD

**Issue by 1xbq1** [DAMO-NLP-SG/VideoLLaMA2#53]
Don't seem to see the download link for the MSVC benchmark dataset? Where can I download it?

**Comment by lixin4ever** [comment]
The annotation file for our MSVC benchmark is available at: https://huggingface.co/datasets/DAMO-NLP-SG/Multi-Source-Video-Captioning. For the raw videos, you need to download them manually according to the provided video ids.

**Comment by 1xbq1** [comment]
Ok, thanks.
