### ISSUE TITLE
Doubt regarding training data

### ISSUE THREAD

**Issue by pritamqu** [DAMO-NLP-SG/VideoLLaMA2#54]
In Table 2, it's mentioned that a total of 12.2M vision-text pairs are used. However, the GitHub repo shares 703K video-text and 558K image-text pairs; Can you share the missing pretraining data?

**Comment by pritamqu** [comment]
A similar mismatch is also noticed for finetuning data as well, would it be possible to share the entire training data?

**Comment by lixin4ever** [comment]
Sorry for the confusion. We may have no plan to release our training data. In the README file, we just provided the pre-training and fine-tuning datasets from Video-LLaVA to demonstrate how to train a VideoLLM with our codebase.

**Comment by pritamqu** [comment]
Thanks for letting me know.
