### ISSUE TITLE
When will the weights of MoE based on Mixtral 8x7B model released?

### ISSUE THREAD

**Issue by ApoorvFrontera** [DAMO-NLP-SG/VideoLLaMA2#61]
Hi Team. I can only see the Mistral model weights but not the Mixtral weights. When will that be available?

**Comment by lixin4ever** [comment]
Hi, the Mixtral-based VideoLLaMA2 has just been released and you can find the weights at VideoLLaMA2's [HF collection](https://huggingface.co/collections/DAMO-NLP-SG/videollama-2-6669b6b6f0493188305c87ed).

**Comment by ApoorvFrontera** [comment]
Thanks
