### ISSUE TITLE
Bug exists during installation.

### ISSUE THREAD

**Issue by CharlesFang207** [DAMO-NLP-SG/VideoLLaMA2#62]
In the 22nd line of the `pyproject.toml` file, it seems it should be `"opencv-python==4.7.0.72", "pysubs2",`, instead of `"opencv-python==4.7.0.72", "pysub2",`.

**Comment by lixin4ever** [comment]
Thank you for pointing out this issue. Just updated the dependency in `pyproject.toml`.
