### ISSUE TITLE
Release about Audio branch

### ISSUE THREAD

**Issue by XuecWu** [DAMO-NLP-SG/VideoLLaMA2#63]
Thank you for your great contributions!

Could you tell me the release schedule of the audio branch?

Looking forward to your reply!

**Comment by lixin4ever** [comment]
Thanks for your kind words. 

We will open-source the audio-language branch for sure but no guarantee for a concrete release date since we are constantly updating the video-language branch (and the audio part is built on top of a well-trained video-language branch)

**Comment by XuecWu** [comment]
> Thanks for your kind words.
> 
> We will open-source the audio-language branch for sure but no guarantee for a concrete release date since we are constantly updating the video-language branch (and the audio part is built on top of a well-trained video-language branch)

Thank you for your timely reply!
Looking forward to the release.

**Comment by xinyifei99** [comment]
Thanks for your attention! You can switch to the audio_visual branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) and clone the repository to train and inference the audio_visual branch.
