### ISSUE TITLE
How to run finetuned model with gradio

### ISSUE THREAD

**Issue by thisurawz1** [DAMO-NLP-SG/VideoLLaMA2#65]
I have already finetuned videollama2 with my custom data. Can you tell me how to run it with GUI ? maybe with gradio

**Comment by clownrat6** [comment]
You can just modify the `model_path` in this script https://github.com/DAMO-NLP-SG/VideoLLaMA2/blob/3a7053aa7b2a4ff9348e46c9e3f0dd0205e3d46e/videollama2/serve/gradio_web_server_adhoc.py#L176
