### ISSUE TITLE
Audio branch

### ISSUE THREAD

**Issue by Morgott-The-Omen-King** [DAMO-NLP-SG/VideoLLaMA2#69]
Hello, authors,

When can we get the Audio-Visual finetuned Video-LLaMA2？Or can we finetune this by ourselves based on the well-visual-finetuned video-llama2?

Thanks in advanced.

**Comment by mfarre** [comment]
I also have the same question: I would like to use videollama2 training code to evaluate some datasets and having the audio part would be very interesting.
Thank you!

**Comment by lixin4ever** [comment]
Hi @Morgott-The-Omen-King @mfarre, the audio-visual finetuned VideoLLaMA2 (dubbed as VideoLLaMA2-AV), is now available, please re-clone our repo and switch to the audio-visual branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) for more details.
