### ISSUE TITLE
Maybe a bug on data preprocess

### ISSUE THREAD

**Issue by Weili-NLP** [DAMO-NLP-SG/VideoLLaMA2#70]
The following code in 'preprocess_plain' function always replace the human instruction with '\<image\>'

https://github.com/DAMO-NLP-SG/VideoLLaMA2/blob/1232384b1d71c8b41517bfa29f75c5f1b2496dc6/videollama2/train.py#L559C17-L559C48

![image](https://github.com/user-attachments/assets/ad9da87f-37fe-48c5-bbff-2897e3b6ad3e)

**Comment by lixin4ever** [comment]
It is not a bug. Pretraining stage is all about image/video-text alignment (rather than instruction following) and this is how it works.

**Comment by Weili-NLP** [comment]
Got it. Thanks for your reply.
