### ISSUE TITLE
Can I use a WAV file as input for inference? 

### ISSUE THREAD

**Issue by FanBu02** [DAMO-NLP-SG/VideoLLaMA2#73]
Can I use a WAV file as input for inference? Could you tell me roughly how to modify the code?

**Comment by xinyifei99** [comment]
Thanks for your attention! You can switch to the audio_visual branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) and clone the repository to run inference for audio related tasks.
