### ISSUE TITLE
What is the difference between VideoLLaMA and VideoLLaMA2 ?

### ISSUE THREAD

**Issue by SeanChenxy** [DAMO-NLP-SG/VideoLLaMA2#8]
Hi, thanks for sharing VideoLLaMA2. Is there any improvement based on VideoLLaMA?

**Comment by lixin4ever** [comment]
Compared to VideoLLaMA, VideoLLaMA2 has improved architecture (STC connector for spatial-temporal modeling), better performances (on both video and audio tasks), and a more user-friendly codebase for training and evaluation.

**Comment by SeanChenxy** [comment]
Thanks for your explanation. How many GPUs do you recommend using for training, evaluation, and inference?

**Comment by lixin4ever** [comment]
Lets take VideoLLaMA2-7B as an example: 
- evaluation & inference: 1*V100-32GB is enough and works fine (actually we do all of the evaluations with fp16 instead of bf16)
- pre-training: 1*A100/A800-80GB should be OK 
- fine-tuning: better no less than 4*A100/A800-80GBs

**Comment by lucasjinreal** [comment]
@lixin4ever  Hi, may I ask the training time with 4*A100? From the code I think it should be extremly slow, since you have almost 80 images into vit, if there is batchSize=10 for training. (images will be expanding to video as well)
