### ISSUE TITLE
Model keeps output "there is no sound/ I can not hear anything" when there is actual sound

### ISSUE THREAD

**Issue by qixueweigitbub** [DAMO-NLP-SG/VideoLLaMA2#80]
Thanks for the great work!

I tested different videos with sound (speech, music, noise etc) using the online demo, but the model keeps ignore the sound information no matter how I asked in the prompt explicitly or implicitly. Is it because the audio file of the video is not loaded properly? Can you help provide any hints here?  Anyone else has the same issue?

**Comment by lixin4ever** [comment]
Sorry for the confusion. The currently available models do not include audio branch and therefore they will not take audio as input.

**Comment by xinyifei99** [comment]
Thanks for your attention! You can switch to the audio_visual branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) and clone the repository to run inference for audio related tasks.

**Comment by LiangMeng89** [comment]
> Thanks for the great work!
> 
> I tested different videos with sound (speech, music, noise etc) using the online demo, but the model keeps ignore the sound information no matter how I asked in the prompt explicitly or implicitly. Is it because the audio file of the video is not loaded properly? Can you help provide any hints here? Anyone else has the same issue?

Hello,I'm a phD student from ZJU, I also use videollama2 to do my own research,we create a WeChat group to discuss some issues of videollama2 and help each other,could you join us? Please contact me: WeChat number == LiangMeng19357260600, phone number == +86 19357260600,e-mail == liangmeng89@zju.edu.cn.
