### ISSUE TITLE
What is the difference between the 'base' and 'chat' versions of a model type?

### ISSUE THREAD

**Issue by Lanbai-eleven** [DAMO-NLP-SG/VideoLLaMA2#85]
What is the difference between the 'base' and 'chat' versions of a model type?

**Comment by clownrat6** [comment]
`Base` version is the `pretraining stage` model weights. Because we only train the projector, the weight repo only contains projector weights. 
'Chat' version is the `supervised finetuning stage` model weights. This stage we tuning projector and LLM, so the weight repo contains whole model weights.

**Comment by Lanbai-eleven** [comment]
> `Base` version is the `pretraining stage` model weights. Because we only train the projector, the weight repo only contains projector weights. `Chat` version is the `supervised finetuning stage` model weights. This stage we tuning projector and LLM, so the weight repo contains whole model weights.

Thx for your explanation！
