### ISSUE TITLE
VideoLLaMA2 performance gap on video benchmarks

### ISSUE THREAD

**Issue by zhuqiangLu** [DAMO-NLP-SG/VideoLLaMA2#92]
Hi,

Please correct me if I am wrong. According to [this comment](https://github.com/DAMO-NLP-SG/VideoLLaMA2/issues/12#issuecomment-2164888883), currently, only vllava dataset is available, while the reported performance is trained on another dataset. 

It seems there is huge performance gap between the same model training on two different datasets (according to table 1 and table 5).

Considering training video llama2 is somehow expensive, could you please provide the performance of video llama2 on each benchmark(a part from those already listed in table 1) ?

Best

**Comment by lixin4ever** [comment]
As discussed in https://github.com/DAMO-NLP-SG/VideoLLaMA2/issues/81, this issue has been resolved and I'm gonna close it.
