### ISSUE TITLE
Can videollama2 continue finetuning on my own dataset using 32 frames?

### ISSUE THREAD

**Issue by zhengrongz** [DAMO-NLP-SG/VideoLLaMA2#93]
Hi! Thanks for your excellent work!
I wonder know whether I can use 32 frames per video to finetune model on my own dataset?
If true, do I just need to change the number of sampled frames in constant?
Looking forward to your reply!

**Comment by lixin4ever** [comment]
Yes, I believe it is fine to do so. In our internal evaluations, we found that our video models can generalize well to longer input (i.e., more input frames), and they usually perform better given the longer input.

You can specify this [argument](https://github.com/DAMO-NLP-SG/VideoLLaMA2/blob/99bce703036a498f8e76a2adb9fd3f50c969beb0/videollama2/train.py#L97) explicitly in your own script to support the training with more video frames.

**Comment by zhengrongz** [comment]
@lixin4ever OK thank you!
