### ISSUE TITLE
When will the audio branch be released?

### ISSUE THREAD

**Issue by XuecWu** [DAMO-NLP-SG/VideoLLaMA2#99]
Thank you for your great contributions!
When will the audio branch be released? I have been waiting for several months...

Looking forward to your reply!
Thanks a lot.

**Comment by XuecWu** [comment]
Could you give us some information on when will the audio branch be released?
I have been waiting for four months...

Thank you for your great work again.

**Comment by xinyifei99** [comment]
Thanks for your attention! You can switch to the audio_visual branch (https://github.com/DAMO-NLP-SG/VideoLLaMA2/tree/audio_visual) and clone the repository to train and inference the audio_visual branch.

**Comment by LiangMeng89** [comment]
> Thank you for your great contributions! When will the audio branch be released? I have been waiting for several months...
> 
> Looking forward to your reply! Thanks a lot.

Hello,I'm a phD student from ZJU, I also use videollama2 to do my own research,we create a WeChat group to discuss some issues of videollama2 and help each other,could you join us? Please contact me: WeChat number == LiangMeng19357260600, phone number == +86 19357260600,e-mail == liangmeng89@zju.edu.cn.
